name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  os_matrix:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, macos-15-intel, windows-latest ]
    runs-on: ${{ matrix.os }}
    name: build ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7
        with:
          gpg_private_key: ${{ secrets.GPG_SUB_SECRET_KEY }}
          passphrase: ${{ secrets.GPG_SUB_SECRET_KEY_PASSWORD }}
          fingerprint: ${{ secrets.GPG_SUB_FINGERPRINT }}
      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: '25'
          distribution: 'liberica'
          java-package: 'jdk+fx'
          cache: ''

      - name: Install gettext on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y gettext

      - name: Install gettext on macOS
        if: matrix.os == 'macos-latest'
        run: brew install gettext

      - name: Install gettext on macOS intel
        if: matrix.os == 'macos-15-intel'
        run: brew install gettext

      - name: Install scoop on Windows
        if: matrix.os == 'windows-latest'
        uses: MinoruSekine/setup-scoop@6435f41324fa55988d8ce5b06bae5cafc75fe045 # v4

      - name: Install gettext on Windows
        if: matrix.os == 'windows-latest'
        run: scoop install gettext

      - name: Build
        env:
          PDFSAM_GPG_FINGERPRINT: ${{ secrets.GPG_SUB_FINGERPRINT }}
        run: mvn clean install -DskipTests -Drelease --batch-mode
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref_name }}
        run: |
          gh release create "$TAG_NAME" \
            --draft \
            autopo-app/target/*.zip \
            autopo-app/target/*.tar.gz \
            autopo-app/target/*.zip.asc \
            autopo-app/*.tar.gz.asc  


